"""Estrutura inicial com Genero e MangaGenero

Revision ID: 444c89e7f4e9
Revises: 
Create Date: 2025-11-08 16:27:39.502521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444c89e7f4e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos',
    sa.Column('id_genero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_genero', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_genero'),
    sa.UniqueConstraint('tipo_genero')
    )
    op.create_table('mangas',
    sa.Column('id_manga', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_manga', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('HIATO', 'CONCLUIDO', 'EM_ANDAMENTO', name='status'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_manga')
    )
    op.create_index(op.f('ix_mangas_titulo_manga'), 'mangas', ['titulo_manga'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('administradores',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('numero_de_mangas_upados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('capitulos',
    sa.Column('id_capitulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_capitulo', sa.String(length=255), nullable=False),
    sa.Column('numero_capitulo', sa.Integer(), nullable=False),
    sa.Column('numero_paginas', sa.Integer(), nullable=False),
    sa.Column('paginas_lidas', sa.Integer(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id_manga'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_capitulo')
    )
    op.create_table('leitores',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codinome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('codinome')
    )
    op.create_table('manga_genero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_genero'], ['generos.id_genero'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id_manga'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id_avaliacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('id_leitor', sa.Integer(), nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.CheckConstraint('nota >= 0.0 AND nota <= 5.0', name='check_nota_range'),
    sa.ForeignKeyConstraint(['id_leitor'], ['leitores.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id_manga'], ),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto_comentario', sa.String(length=1000), nullable=False),
    sa.Column('numero_curtidas', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('id_leitor', sa.Integer(), nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_leitor'], ['leitores.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id_manga'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('leitor_manga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_leitor', sa.Integer(), nullable=False),
    sa.Column('id_manga', sa.Integer(), nullable=False),
    sa.Column('data_favorito', sa.DateTime(), nullable=True),
    sa.Column('progresso_leitura', sa.Float(), nullable=True),
    sa.Column('ultimo_capitulo_lido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_leitor'], ['leitores.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id_manga'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leitor_manga')
    op.drop_table('comentarios')
    op.drop_table('avaliacoes')
    op.drop_table('manga_genero')
    op.drop_table('leitores')
    op.drop_table('capitulos')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_mangas_titulo_manga'), table_name='mangas')
    op.drop_table('mangas')
    op.drop_table('generos')
    # ### end Alembic commands ###
